### ISSUE TITLE
Incorrect `tempFilePath` on Linux

### ISSUE THREAD

**Issue by JarrodDoyle** [JRiggles/Lospec-Palette-Importer#1]
The importer fails for me due to using `/tmppalettedata.tmp` rather than `/tmp/palettedata.tmp`. The API [docs](https://www.aseprite.org/api/app_fs#appfstemppath) suggest that's expected for both Mac and Linux so it should be safe to just put a `/` before `palettedata.tmp` on line 191.

**Comment by JRiggles** [comment]
Thanks for the report! I'm chasing this bug down presently and this is very helpful.
