### ISSUE TITLE
Nothing happens when running script

### ISSUE THREAD

**Issue by hsandt** [JRiggles/Lospec-Palette-Importer#3]
I ran Scripts > lospec-palette-importer (folder) > lospec-palette-importer and confirm I want to run the script, but nothing happens.

No error shown when running `aseprite` from terminal.

**Comment by JRiggles** [comment]
Hi @hsandt - sorry for the delay, I'm just seeing this. I should clarify, this is an Aseprite extension (basically a plugin), not a script; you don't run it from the scripts menu. You can run the extension from the palette menu as shown in [this screenshot](https://github.com/JRiggles/Lospec-Palette-Importer/blob/main/screenshots/palette%20menu%20selection.png). If you downloaded the extension from itch.io, you can double-click on the `lospec-palette-importer.aseprite-extension` file to install it.

**Comment by JRiggles** [comment]
@hsandt Hi again. I just wanted to check in to see if you are still running into this issue! Let me know, otherwise I'll go ahead and close this.

**Comment by JRiggles** [comment]
Closing this as there hasn't been any further info.
