### ISSUE TITLE
Open in app no longer working

### ISSUE THREAD

**Issue by doomercreatine** [JRiggles/Lospec-Palette-Importer#4]
Installed most recent extension the other day. It worked that day where I'd hit "Open in app..." on lospec and it would open as expected. Now today it no longer does that. I have to manually run the extension each time in Aseprite. Uninstalling and reinstalling the extension has not worked. do you have a list of the registry keys added that we can remove for a full reset?

**Comment by JRiggles** [comment]
@doomercreatine Thanks for the heads up! I'll look  into it later tonight if I have a moment.

For transparency: when you click on the "Open in App" link on Lospec, the URI handler runs [this script](https://github.com/JRiggles/Lospec-Palette-Importer/blob/main/extension/WindowsHelper/URIHandler.cmd). That script relies on an environment variable `%ASEPRITE_EXECUTABLE%` which gets set the *first time you run the extension manually* (that is, from within Aseprite); it tells the script where Aseprite is installed. 

**The gist is you need to run the extension _at least once_ from Aseprite for the URI handler to work. After that, the "Open in App" links on Lospec should launch Aseprite and the Extension automatically.**

My recommendations are:
- delete the `HKEY_CLASSES_ROOT\lospec-palette` registry key (optional - this is the URI handler registration)
- uninstall the Lospec Palette Importer extension
- reinstall the extension
- run it from Aseprite once
- try opening a `//lospec-palette` URI from the website

Let me know if that works for you!

**Comment by JRiggles** [comment]
@doomercreatine I was able to confirm that the URI handler is still working on my Windows 11 machine running the Steam version of Aseprite 1.3.10 (latest stable at time of writing).

Could you open Command Prompt, run this command, and let me know what it prints?
`echo %ASEPRITE_EXECUTABLE%` (not case-sensitive)

You should see something like:
`D:\SteamLibrary\steamapps\common\Aseprite\Aseprite.exe` (or wherever you have Aseprite installed)

If that environment variable is set properly, it's possible there's an issue with the URI handler registration. If it *isn't* set, running the extension from Aseprite should set it for you - you can try the `echo` again after doing so to confirm. 

_Alternatively_, you could use the command `set ASEPRITE_EXECUTABLE="<the absolute path to Aseprite.exe on your machine>"` to set the environment variable manually (though that shouldn't be necessary).

**Comment by JRiggles** [comment]
Fixed in v1.5.0
